// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("XRoadLib")]
[assembly: AssemblyProductAttribute("XRoadLib")]
[assembly: AssemblyDescriptionAttribute("A .NET library for implementing service interfaces of X-Road providers using Code-First Development approach.")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0-beta019")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
        internal const string InformationalVersion = "1.0.0-beta019";
    }
}
