// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("XRoadLib")]
[assembly: AssemblyProductAttribute("XRoadLib")]
[assembly: AssemblyDescriptionAttribute("A .NET library for implementing service interfaces of X-Road providers using Code-First Development approach.")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: InternalsVisibleToAttribute("XRoadLib.Tests, PublicKey=00240000048000009400000006020000002400005253413100040000010001008d1875f0fa838e308de6846cf68cd6c7dca1a6e5053754a95084907da06dd01ed486b77e4a4a52c5140a849a0737b9301de3261d5180ef7938789856a04990b54b9d57e35fa8da8d61c4e98fd4eb0079b28eca20265da68f8885bee9fc9ba4c3782eb428caa0c84ce4c4c4bea2111e7b925dc69a6fef2b2ec9aa0ad0bd4a88f1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
