name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 5.0.x
      - name: Install tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: Run tests
        run: dotnet fake run build.fsx target RunTests

  windows-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 5.0.x
      - name: Install tools
        run: dotnet tool restore
      - name: Setup strong name key
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          [IO.File]::WriteAllBytes("${{ github.workspace }}\src\XRoadLib.snk", [Convert]::FromBase64String($env:TEST))
          type ${{ github.workspace }}\src\XRoadLib.snk
      - name: Install dependencies
        run: dotnet restore
      - name: Run tests
        run: dotnet fake run build.fsx target RunTests
        
